### ISSUE TITLE
i need Sample code

### ISSUE THREAD

**Issue by pishguy** [shubham-gupta-16/view_model_x#1]
how can we pass variables whole application such as `Bloc` or `Provider`?

**Comment by shubham16g** [comment]
The sample code is present in example tab. 
You can find it at example/lib/main.dart

**Comment by pishguy** [comment]
yes that's right, but i can't find any implementation about my question there

**Comment by shubham16g** [comment]
@pishguy In the example, I just wrap the `HomePageContent()` widget.

You can wrap the `MaterialApp` with `ViewModelProvider` and pass your custom view-model there. Now, you can get your view-model instance from anywhere by calling `ViewModelProvider.of<CustomViewModel>(context)`.

**Comment by shubham16g** [comment]
@pishguy Reply, is your problem solved. If not, explain more so I can understand the problem correctly.
I will be happy to help.

**Comment by shubham16g** [comment]
One more thing, I will add `MiltiViewModelProvider` class in the next update.

I will also release a YouTube video demonstrating how it works and how it is better than other state management package.

**Comment by shubham16g** [comment]
@pishguy Newer Version `0.2.0` is released.
https://pub.dev/packages/view_model_x
I recommend using this as the older version had some major bugs which are fixed now.

**Comment by pishguy** [comment]
@shubham-gupta-16 unfortunately i can't test yet, but I'll test as soon. could you please add some sample code to how can we use restful api?

**Comment by shubham16g** [comment]
> @shubham-gupta-16 unfortunately I can't test yet, but I'll test as soon. could you please add some sample code to how can we use restful API?

Ok, I will add an entire MVVM sample code in the example by the end of the day.

**Comment by shubham16g** [comment]
@pishguy Two Newer Version `0.2.1` and `0.3.0` are released.
In the latest release, I added the `MultiViewModelProvider`. Example code is also improved and documentation is as well.

Check the live demo of the example project:
https://shubham-gupta-16.github.io/view_model_x/

**Comment by shubham16g** [comment]
I will add the MVVM example very soon.

**Comment by pishguy** [comment]
@shubham-gupta-16 thanks so much. i tested your sample code, that works fine :)
