### ISSUE TITLE
Why storing the viewmodel in StatelessWidget?

### ISSUE THREAD

**Issue by hilmanshini** [shubham-gupta-16/view_model_x#13]
I noticed all of the example here are using the concept ViewModel which is good,
but i dont know why you store all of the viewmodel (that encapsulate the logic)  in StatelessWidget
as i know the StatelessWidget is a class that should never handle the state and variable, but
once you put the viewmodel in statelesswidget that store the data and can put the viewmodel (logic) on it 
the statefulwidget will become useless, am i right? 
so , is it true that if i have to use this library i should never use the statefulwidget? or can i use statefullwidget along with viewmodel?

**Comment by shubham16g** [comment]
@hilmanshini It depends on what your use case. If you have used a provider(ChangeNotifier) or Bloc, they doesn't require to use a stateful widget to handle the state and update the UI. 

You can use a stateless widget along with builders or watch.
